[dev]
  command = "npm run vite:start"
  publish = "dist"
  # We need another port for the application because Vite occupies the 3000.
  port = 8080

[build]
  command = "npm run vite:build"
  publish = "dist"

[functions]
  # We are goint to use ES modules so we need esbuild to transpile the code.
  node_bundler = "esbuild"

# We have to tell the Netlify that this URL will be served by the books.js function.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200